# Generated by Django 3.2.3 on 2021-06-11 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('PAN_number', models.CharField(max_length=10)),
                ('Age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'not specified')], max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=100)),
            ],
        ),
    ]
